{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [30/Apr/2020 16:17:24] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Apr/2020 16:17:27] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-04-30 16:17:31,484] ERROR in app: Exception on /load_data/9294158/2.0/ [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\pandas\\core\\indexes\\base.py\", line 2646, in get_loc\n",
      "    return self._engine.get_loc(key)\n",
      "  File \"pandas\\_libs\\index.pyx\", line 111, in pandas._libs.index.IndexEngine.get_loc\n",
      "  File \"pandas\\_libs\\index.pyx\", line 138, in pandas._libs.index.IndexEngine.get_loc\n",
      "  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item\n",
      "  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 1622, in pandas._libs.hashtable.PyObjectHashTable.get_item\n",
      "KeyError: 'tt10136626'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-b99ea5eb759c>\", line 58, in load_data\n",
      "    df = make_data(ids, std)\n",
      "  File \"<ipython-input-1-b99ea5eb759c>\", line 74, in make_data\n",
      "    show_obj.create_df()\n",
      "  File \"<ipython-input-1-b99ea5eb759c>\", line 120, in create_df\n",
      "    self.df = self.get_ratings(df)\n",
      "  File \"<ipython-input-1-b99ea5eb759c>\", line 123, in get_ratings\n",
      "    df['rating'] = df['code'].apply(lambda x: ratings.loc[x, :].values)\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\pandas\\core\\series.py\", line 3849, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-1-b99ea5eb759c>\", line 123, in <lambda>\n",
      "    df['rating'] = df['code'].apply(lambda x: ratings.loc[x, :].values)\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\pandas\\core\\indexing.py\", line 1760, in __getitem__\n",
      "    return self._getitem_tuple(key)\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\pandas\\core\\indexing.py\", line 1270, in _getitem_tuple\n",
      "    return self._getitem_lowerdim(tup)\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\pandas\\core\\indexing.py\", line 1387, in _getitem_lowerdim\n",
      "    section = self._getitem_axis(key, axis=i)\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\pandas\\core\\indexing.py\", line 1963, in _getitem_axis\n",
      "    return self._get_label(key, axis=axis)\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\pandas\\core\\indexing.py\", line 624, in _get_label\n",
      "    return self.obj._xs(label, axis=axis)\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\pandas\\core\\generic.py\", line 3536, in xs\n",
      "    loc = self.index.get_loc(key)\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\pandas\\core\\indexes\\base.py\", line 2648, in get_loc\n",
      "    return self._engine.get_loc(self._maybe_cast_indexer(key))\n",
      "  File \"pandas\\_libs\\index.pyx\", line 111, in pandas._libs.index.IndexEngine.get_loc\n",
      "  File \"pandas\\_libs\\index.pyx\", line 138, in pandas._libs.index.IndexEngine.get_loc\n",
      "  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item\n",
      "  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 1622, in pandas._libs.hashtable.PyObjectHashTable.get_item\n",
      "KeyError: 'tt10136626'\n",
      "127.0.0.1 - - [30/Apr/2020 16:17:31] \"\u001b[37mPOST /load_data/9294158/2.0/ HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Apr/2020 16:17:32] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Apr/2020 16:17:35] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-04-30 16:17:40,555] ERROR in app: Exception on /load_data/0132218/2.0/ [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\pandas\\core\\indexes\\base.py\", line 2646, in get_loc\n",
      "    return self._engine.get_loc(key)\n",
      "  File \"pandas\\_libs\\index.pyx\", line 111, in pandas._libs.index.IndexEngine.get_loc\n",
      "  File \"pandas\\_libs\\index.pyx\", line 138, in pandas._libs.index.IndexEngine.get_loc\n",
      "  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item\n",
      "  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 1622, in pandas._libs.hashtable.PyObjectHashTable.get_item\n",
      "KeyError: 'tt0866650'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-b99ea5eb759c>\", line 58, in load_data\n",
      "    df = make_data(ids, std)\n",
      "  File \"<ipython-input-1-b99ea5eb759c>\", line 74, in make_data\n",
      "    show_obj.create_df()\n",
      "  File \"<ipython-input-1-b99ea5eb759c>\", line 120, in create_df\n",
      "    self.df = self.get_ratings(df)\n",
      "  File \"<ipython-input-1-b99ea5eb759c>\", line 123, in get_ratings\n",
      "    df['rating'] = df['code'].apply(lambda x: ratings.loc[x, :].values)\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\pandas\\core\\series.py\", line 3849, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas\\_libs\\lib.pyx\", line 2327, in pandas._libs.lib.map_infer\n",
      "  File \"<ipython-input-1-b99ea5eb759c>\", line 123, in <lambda>\n",
      "    df['rating'] = df['code'].apply(lambda x: ratings.loc[x, :].values)\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\pandas\\core\\indexing.py\", line 1760, in __getitem__\n",
      "    return self._getitem_tuple(key)\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\pandas\\core\\indexing.py\", line 1270, in _getitem_tuple\n",
      "    return self._getitem_lowerdim(tup)\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\pandas\\core\\indexing.py\", line 1387, in _getitem_lowerdim\n",
      "    section = self._getitem_axis(key, axis=i)\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\pandas\\core\\indexing.py\", line 1963, in _getitem_axis\n",
      "    return self._get_label(key, axis=axis)\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\pandas\\core\\indexing.py\", line 624, in _get_label\n",
      "    return self.obj._xs(label, axis=axis)\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\pandas\\core\\generic.py\", line 3536, in xs\n",
      "    loc = self.index.get_loc(key)\n",
      "  File \"C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\pandas\\core\\indexes\\base.py\", line 2648, in get_loc\n",
      "    return self._engine.get_loc(self._maybe_cast_indexer(key))\n",
      "  File \"pandas\\_libs\\index.pyx\", line 111, in pandas._libs.index.IndexEngine.get_loc\n",
      "  File \"pandas\\_libs\\index.pyx\", line 138, in pandas._libs.index.IndexEngine.get_loc\n",
      "  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item\n",
      "  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 1622, in pandas._libs.hashtable.PyObjectHashTable.get_item\n",
      "KeyError: 'tt0866650'\n",
      "127.0.0.1 - - [30/Apr/2020 16:17:40] \"\u001b[37mPOST /load_data/0132218/2.0/ HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Apr/2020 16:17:41] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Apr/2020 16:17:44] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Apr/2020 16:17:49] \"\u001b[37mPOST /load_data/1740835/2.0/ HTTP/1.1\u001b[0m\" 200 -\n",
      "C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\plotnine\\ggplot.py:729: PlotnineWarning: Saving 6.4 x 4.8 in image.\n",
      "  from_inches(height, units), units), PlotnineWarning)\n",
      "C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\plotnine\\ggplot.py:730: PlotnineWarning: Filename: static/visual5055.png\n",
      "  warn('Filename: {}'.format(filename), PlotnineWarning)\n",
      "C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\plotnine\\stats\\smoothers.py:168: PlotnineWarning: Confidence intervals are not yet implementedfor lowess smoothings.\n",
      "  \"for lowess smoothings.\", PlotnineWarning)\n",
      "127.0.0.1 - - [30/Apr/2020 16:17:51] \"\u001b[37mPOST /output/ HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Apr/2020 16:17:52] \"\u001b[37mGET /static/visual5055.png HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Apr/2020 16:17:54] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Apr/2020 16:18:00] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Apr/2020 16:18:14] \"\u001b[37mPOST /load_data/0386676/1.7/ HTTP/1.1\u001b[0m\" 200 -\n",
      "C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\plotnine\\ggplot.py:729: PlotnineWarning: Saving 6.4 x 4.8 in image.\n",
      "  from_inches(height, units), units), PlotnineWarning)\n",
      "C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\plotnine\\ggplot.py:730: PlotnineWarning: Filename: static/visual1886.png\n",
      "  warn('Filename: {}'.format(filename), PlotnineWarning)\n",
      "C:\\Users\\calla\\Anaconda3\\envs\\pyMain\\lib\\site-packages\\plotnine\\stats\\smoothers.py:168: PlotnineWarning: Confidence intervals are not yet implementedfor lowess smoothings.\n",
      "  \"for lowess smoothings.\", PlotnineWarning)\n",
      "127.0.0.1 - - [30/Apr/2020 16:18:28] \"\u001b[37mPOST /output/ HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Apr/2020 16:18:28] \"\u001b[37mGET /static/visual1886.png HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Apr/2020 16:18:39] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask, request, render_template, redirect, url_for\n",
    "from wtforms import Form, validators, TextField\n",
    "from imdb import IMDb\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from plotnine import *\n",
    "import requests, os, io, random\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "global imdb, ratings\n",
    "ratings = pd.read_csv('files/title.ratings.csv')\n",
    "ratings = ratings.set_index(['tconst'])\n",
    "imdb = IMDb()\n",
    "\n",
    "\n",
    "@app.route('/output/', methods=['GET', 'POST'])\n",
    "def display_output():\n",
    "    \n",
    "    files = [file for file in os.listdir('static') if file.endswith('.png')]\n",
    "    [os.remove('static/'+ filename) for filename in files]\n",
    "    \n",
    "    if request.method == 'POST':\n",
    "        \n",
    "        plot, filename, title = make_chart(df)\n",
    "        \n",
    "        return render_template('output.html', name = title, url = filename)\n",
    "    return render_template('wait_page.html')\n",
    "\n",
    "\n",
    "class Show_choices(Form):\n",
    "    show = TextField('Show:', validators=[validators.DataRequired()])\n",
    "\n",
    "@app.route('/', methods=['GET', 'POST'])\n",
    "def index():        \n",
    "    form = Show_choices(request.form)\n",
    "    \n",
    "    if request.method == 'POST':\n",
    "        choice = request.form['show']\n",
    "        results = imdb.search_movie(choice)\n",
    "        names = [show['title'] for show in results if show['kind'] == 'tv series']\n",
    "        year = [show['year'] for show in results if show['kind'] == 'tv series']\n",
    "        urls = [show['full-size cover url'] for show in results if show['kind'] == 'tv series']\n",
    "        ids = [imdb.get_imdbID(show) for show in results if show['kind'] == 'tv series']\n",
    "        \n",
    "        return render_template('verify_show.html', choice = choice, urls = urls,\n",
    "                               year = year, names = names, length = len(names), ids = ids)\n",
    "    return render_template('index.html')\n",
    "\n",
    "@app.route('/load_data/<ids>/<std>/', methods=['GET', 'POST'])\n",
    "def load_data(ids, std):\n",
    "    if request.method == 'POST':\n",
    "        \n",
    "        global df\n",
    "        df = make_data(ids, std)\n",
    "        \n",
    "        return render_template('wait_page.html')\n",
    "    return render_template('verify_show.html')\n",
    "\n",
    "\n",
    "@app.errorhandler(500)\n",
    "def page_not_found(e):\n",
    "    # note that we set the 404 status explicitly\n",
    "    return render_template('python_error.html')\n",
    "\n",
    "def make_data(ids, std):\n",
    "    show = imdb.get_movie(ids)\n",
    "    imdb.update(show, info = ['episodes'])\n",
    "\n",
    "    show_obj = show_series(show)\n",
    "    show_obj.create_df()\n",
    "    show_obj.calc_outliers(sd=std)\n",
    "\n",
    "    df = show_obj.df\n",
    "    df['combined_labs'] = df['title'] + \"\\nS \" + df['season'].astype(str) + \" | E \" + df['episode'].astype(str)\n",
    "    return df\n",
    "\n",
    "def make_chart(df):\n",
    "    outlier_index = df[df['outlier']==True].index.tolist()\n",
    "    plot = (ggplot(df, aes(y='rating', x=df.index.tolist()))\n",
    "            + geom_smooth(color='lightblue', size = 2)\n",
    "            + geom_point(aes(color = 'factor(season)'), size = 2)\n",
    "            + geom_label(aes(x = outlier_index,\n",
    "                            y = df[df['outlier']==True]['rating'].values,\n",
    "                            label = 'combined_labs'),\n",
    "                        data = df[df['outlier']==True], size = 6, show_legend = False, alpha = .7, fill = 'gray',\n",
    "                        adjust_text={'expand_points':(1.5, 1.5), 'expand_text':(2, 2), 'arrowprops': {'arrowstyle': '-'}})\n",
    "            + labs(x = 'Episode Number', y = 'IMDb Rating', color = \"Season\")\n",
    "            + theme_classic())\n",
    "    \n",
    "    filename = 'visual' + str(random.randrange(1,10000)) + '.png'\n",
    "    plot.save(filename = 'static/' +  filename)\n",
    "    title = str(df['series'].unique()[0])\n",
    "    return plot, filename, title\n",
    "\n",
    "class show_series():\n",
    "    def __init__(self, show):\n",
    "        self.show = show\n",
    "\n",
    "    def create_df(self):\n",
    "        season, episode, title, year, series, code = [], [], [], [], [], []\n",
    "        for x in self.show['episodes'].keys():\n",
    "            for y in self.show['episodes'][x].keys():\n",
    "                thing = self.show['episodes'][x][y]\n",
    "                try:\n",
    "                    year.append(thing['year'])\n",
    "                    title.append(thing['title'])\n",
    "                    series.append(self.show['title'])\n",
    "                    code.append(\"tt\" + imdb.get_imdbID(thing))\n",
    "                    season.append(x)\n",
    "                    episode.append(y)\n",
    "                except:\n",
    "                    pass\n",
    "        df_dict = {'season':season, 'episode':episode, 'title':title, 'year':year, 'series':series, 'code':code}\n",
    "        df = pd.DataFrame(df_dict).sort_values(by=['season', 'episode']).reset_index(drop=True)\n",
    "        df.index += 1\n",
    "        self.df = self.get_ratings(df)\n",
    "        \n",
    "    def get_ratings(self, df):\n",
    "        df['rating'] = df['code'].apply(lambda x: ratings.loc[x, :].values)\n",
    "        df = df[df['rating'].apply(lambda x: len(x)) > 0]\n",
    "        df['votes'] = df['rating'].apply(lambda x: x[1])\n",
    "        df['rating'] = df['rating'].apply(lambda x: x[0])\n",
    "        return df\n",
    "    \n",
    "    def calc_outliers(self, column = 'rating', sd = 2):\n",
    "        groups = self.df.groupby('season')[column]\n",
    "        groups_mean = groups.transform('mean')\n",
    "        groups_std = groups.transform('std')\n",
    "        self.df['outlier'] = self.df[column].between(groups_mean.sub(groups_std.mul(float(sd))),\n",
    "                      groups_mean.add(groups_std.mul(float(sd))))\n",
    "        self.df['outlier'] = [ True if x == False else False for x in self.df['outlier'] ]\n",
    "\n",
    "\n",
    "        \n",
    "if __name__ == '__main__':\n",
    "    app.run(use_reloader=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
